name = "RigorousCoupledWaveAnalysis"
uuid = "c8f76c1c-e1da-11e9-2f58-db462fa08db6"
authors = ["jonschlipf <schlipf.jon@gmx.net>"]
version = "1.0.2"

[compat]
FFTW="1"
Interpolations="0.13"
julia="1" 

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
